#! /bin/bash

getpath() {
	local rr=$(./src/main.py)
	echo $rr
	eval $rr
	echo -e "$RESULT"
	if [[ -d "$RESULT" ]]; then
		echo "is a path"
	else
		echo "not a path"
	fi

	local want="/home/miko/Projects/Texp" 
	echo $want

	echo -e "$want\n$RESULT\n$rr\nxxx" > tmp.log
	if [[ "$want" == $RESULT ]]; then
		echo "same"
	else
		echo "diff"
													fi
																														
	if [[ -d "$want" ]]; then
		echo "bin is a path"
	fi
}

getpath

